const languages = [
	{
		idx: 0,
		languageName: 'Español',
		language:'Lenguaje',
		name: 'Nombre',
		level:'Nivel',
		type:'Tipo',
		keywords:'♦ Palabras clave',
		action:'Acción',
		range:'Rango',
		description:'Descripción',
		icon:'Ícono',
		add:'Agregar propiedad',
		property:'Propiedad',
		types:[
			'A-Voluntad',
			'Encuentro',
			'Diario'
		],
		actions: [
			'Acción estándar',
			'Acción de movimiento',
			'Acción menor',
			'Acción gratuita',
			'Acción inmediata',
			'Acción de oportunidad'
		],
		gradient: 'Gradiente',
		iconsLetters: [
			'a',
			'c',
			'm',
			'r',
			'A',
			'C',
			'M',
			'R',
			'@',
			'',
		],
		iconsDescriptions:[
			'Ataque de área básico',
			'Ataque cercano básico',
			'Ataque c/c básico',
			'Ataque a distancia básico',
			'Ataque de área',
			'Ataque cercano',
			'Ataque c/c',
			'Ataque a distacia',
			'Aura',
			'Ninguno',
		]
	},
	{
		idx: 1,
		languageName: 'English',
		language:'Language',
		name: 'Name',
		level:'Level',
		type:'Type',
		keywords:'♦ Keywords',
		action:'Action',
		range:'Range',
		description:'Description',
		icon:'Icon',
		add:'Add property',
		property:'Property',
		types:[
			'At-Will',
			'Encounter',
			'Daily'
		],
		actions: [
			'Standar action',
			'Movement action',
			'Minor action',
			'Free action',
			'Immediate action',
			'Opportunity action'
		],
		gradient: 'Gradient',
		iconsLetters: [
			'a',
			'c',
			'm',
			'r',
			'A',
			'C',
			'M',
			'R',
			'@',
			'',
		],
		iconsDescriptions:[
			'Area basic attack',
			'Close basic attack',
			'Melee basic attack',
			'Ranged basic attack',
			'Area attack',
			'Close attack',
			'Melee attack',
			'Ranged attack',
			'Aura',
			'None',
		]
	},
]
export default languages;
